spring:
  jpa:
    show-sql: false
    database: h2
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:~/search"
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      # default 값이 /actuator endpoint는 외부에 잘 알려져 있어 보안을 위해 다른 endpoint 사용
      base-path: /monitor
      # 마찬가지 이유로 /health endpoint 대신 다른 endpoint 사용
      path-mapping:
        health: health_check
      exposure:
        # 보안을 위해 health check 하는 endpoint만 exposure
        include: health
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true

kakao:
  api-key: ${KAKAO_API_KEY}

naver:
  client-id : ${NAVER_CLIENT_ID}
  client-secret : ${NAVER_CLIENT_SECRET}