name: Build and test

on:
  # master 브랜치에 PR이 생성되면 수행 됨
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build spring boot application
        uses: gradle/gradle-build-action@v2
        # build 명령어에 compile, bootJar, test 포함됨
        with:
          arguments: build